# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = 'gruvbox_dark'

format = '${custom.conditional_time}$all$line_break$character'
[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[custom.conditional_time]
command = '''
if [ "$PWD" != "$HOME" ]; then
    date "+%H:%M"
fi
'''
when = true
format = '[$output](bold color_purple) '

[git_branch]
symbol = ""
format = '[$symbol $branch ](bold color_orange)'

[character]
disabled = false
success_symbol = '[⟶](bold color_green)'
error_symbol = '[⟶](bold color_red)'
vimcmd_symbol = '[⟵](bold color_aqua)'
vimcmd_replace_one_symbol = '[⟵](bold color_purple)'
vimcmd_replace_symbol = '[⟵](bold color_purple)'
vimcmd_visual_symbol = '[⟵](bold color_yellow)'
