# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Palette should be at root level
palette = 'gruvbox_dark'

format = '$time$all$line_break$character'
[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[time]
disabled = false
format = '[$time](bold color_purple) '
time_format = '%H:%M'
[git_branch]
symbol = ""
format = '[$symbol $branch](bold color_orange)'

[character]
disabled = false
success_symbol = '[⟶](bold color_green)'
error_symbol = '[⟶](bold color_red)'
vimcmd_symbol = '[⟵](bold color_green)'
vimcmd_replace_one_symbol = '[⟵](bold color_purple)'
vimcmd_replace_symbol = '[⟵](bold color_purple)'
vimcmd_visual_symbol = '[⟵](bold color_yellow)'
