# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
[character]
disabled = false
success_symbol = '[⟶](bold green)'
error_symbol = '[⟶](bold red)'
vimcmd_symbol = '[⟵](bold green)'
vimcmd_replace_one_symbol = '[⟵](bold purple)'
vimcmd_replace_symbol = '[⟵](bold purple)'
vimcmd_visual_symbol = '[⟵](bold yellow)'
