# Backend
backend = "glx";
vsync = true;


# Rounded corners
corner-radius = 8;
rounded-corners-exclude = [
    "class_g = 'polybar'"
];

# Opacity
inactive-opacity = 0.98;
active-opacity = 0.98;
opacity-rule = [
    "100:class_g = 'firefox'",
    "100:class_g = 'vlc'"
];
